[package]
name = "semtech-udp"
version = "0.1.0"
authors = ["Louis Thiery <louis@helium.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mio = "0.6"
num_enum = "0.4"
arrayref = "0.3"
serde_json = "1.0"